# Generated by Django 5.1.2 on 2024-12-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='discusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro.discucion'),
        ),
    ]
